### ISSUE TITLE
remove obscure adduser workaround

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#106]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006899

 adduser (3.121) unstable; urgency=medium

* Invoke the "crontab" command with the proper syntax. (Closes: #1006899)

**Comment by nabijaczleweli** [comment]
governed by
```cpp
	// deluser in adduser package expects this behaviour
case action_t::list:
case action_t::remove:
case action_t::edit:
	user = argv[optind];
	break;
```

seems fixed in https://salsa.debian.org/debian/adduser/-/commit/d512410a466c465fd9615a8a8248c1b40324869c and there don't appear to be any more blunders like this on salsa HEAD

(unfortunately DCS isn't all that helpful in finding any other mishaps like this)

Removed in c800d4d0a17c7786ec7a72f280983f590f27219f
