### ISSUE TITLE
python EndGame

### ISSUE THREAD

**Issue by a-detiste** [systemd-cron/systemd-cron#108]
- [x] 2023/08/16: upload 1.16.7-1 to unstable
- [x] 2023/08/16: upload 2.0-2 to experimental
- [x] 2023/08/24: 1.16.7-1 migrates to testing, delay shortened by presence of autopkgtests
- [x] 2023/08/28: upload 2.0.1-2 to unstable
- [x] 2023/09/01: 2.0.01-2 in testing
- [ ] 2023/11: ask for a backport to BookWorm at MiniDebConf Cambridge

---

things out of my control:
- [ ] new unexpected bugs
- [x] Debian: end of moratorium -> package is BinNMU-able thanks to `pkgconf` integration.
- [ ] Debian: move Salsa git under systemd team
- [x] Arch package update
- [x] Gentoo package update
- [x] OpenMemba package update

**Comment by a-detiste** [comment]
I need this backport for my job. It wouldn't go in the main archive but in the `backports` one.
Only critical bugs get fixed in `stable`.

**Comment by a-detiste** [comment]
`adduser` was fixed before bookworm was released

**Comment by rich0** [comment]
RE packaging (at least on Gentoo) - is there some indicator as to what versions are intended to be experimental / unstable / stable from an upstream perspective?  I might work on a masked ebuild for v2 now that is available, but being system-related I'll probably avoid releasing it on our testing community until there is some kind of indication that it has settled down.  

I did notice the checklist above which is why I'm asking - I don't see it anywhere more prominent.  In any case my goal would be to try to align our releases with the ones considered intended for adoption.  I keep my eye on repology in any case.

**Comment by a-detiste** [comment]
Than you for caring .... what you can't know is that this planning is
tightly bound to my Holiday.

2.0 went in Debian expérimental.

The interresting parts do work (much better !) but we are facing problems
with the integration tests.
And some rare build failure due to races conditions in the Majefile.

So anyway for you it would be better to wait for a 2.0.1 release.

The last 1.x release incluses all the fixes we could backport while doing
v2.0.

Greetings

**Comment by a-detiste** [comment]
Thanks to pkgconf intégration,
the Debian package can be rebuilt
(binNMU) without my intervention
for the final step of the UsrMerge

наб has the key of the kingdom
(the upstream repo)

**Comment by rich0** [comment]
RE pkgconf, ideally the configure script should check PKG_CONFIG in the environment and fallback to pkgconf if it is unset.  There can be alternative implementations of it/etc.

I'll hold off on pushing out 2.0, though if I get a chance I might start on packaging it.

**Comment by nabijaczleweli** [comment]
9261c5f

**Comment by a-detiste** [comment]
@rich0 v2.0.1 is gold

**Comment by rich0** [comment]
Thanks for the heads-up.  I do have a working package for it in my own repo.  I'm going to hold off on deploying it to the Gentoo repo until it is at least considered unstable/testing.  Unfortunately it doesn't seem like the test suite is compatible with our package manager so I had to disable automated testing (probably a sandboxing issue with the use of namespaces/unshare - which otherwise seems like a good idea).  I might fiddle with it at some point to see if it can be made to work.

In any case, it should be a pretty quick deployment once it is ready.

**Comment by a-detiste** [comment]
The 'tests:' target could depends on 'unittests:' and 'integrationtests:' (the one that requires unshare).[*]

I had personaly never heard of unshare before and it is not supported on Debian build servers, only on CI testbed servers.

[*] then we and in packaging "overide_dh_auto_test:
         make unit_test"

Greetings

Nonrush needed here

**Comment by nabijaczleweli** [comment]
The tests all say what they need at the top:
```
==> test/test-generator <==
#!/bin/sh
# expects to run as root of a mountns

==> test/test-m_o_f <==
#!/bin/sh
# needs to run as root of a UTS namespace to set hostname

==> test/test-r_s_s <==
#!/bin/sh
# expects to run as root of a mountns
```

`make test` is a simple developer recipe to drive them correctly:
```sh
unshare -rm test/test-generator $(enable_runparts) "$(statedir)"
unshare -ru test/test-m_o_f $(version)
unshare -rm test/test-r_s_s
```

If your infrastructure doesn't let you `unshare(CLONE_NEWUSER)` because you're in a chroot (i.e. your `/` is different from your mount namespace's `/`), skip them by exporting S_C_G, M_O_F, R_S_S as "skip" and drive them manually.

On Debian buildds unshare isn't "unsupported" like alexandre says, but the builds *do* run in a chroot, so they must be granted root from their host instead of inventing their own – see https://salsa.debian.org/detiste-guest/systemd-cron/-/tree/master/debian/tests, which drives them as
```sh
S_C_G=/lib/systemd/system-generators/systemd-crontab-generator exec unshare -rm test/test-generator no /var/spool/cron/crontabs
M_O_F=/usr/libexec/systemd-cron/mail_on_failure                exec unshare -ru test/test-m_o_f "$(dpkg-parsechangelog -SVersion)"
R_S_S=/usr/libexec/systemd-cron/remove_stale_stamps            exec unshare -rm test/test-r_s_s
```

**Comment by nabijaczleweli** [comment]
I've split the tests into test-nounshare/test-unshare in f62ed882e5deadc836cac0ca3d90a1c7579f73b2 instead of the `skip` thing (https://salsa.debian.org/detiste-guest/systemd-cron/-/merge_requests/8).

**Comment by a-detiste** [comment]
@rich0 

> Unfortunately it doesn't seem like the test suite is compatible with our package manager so I had to disable automated testing (probably a sandboxing issue with the use of namespaces/unshare - which otherwise seems like a good idea).

The test suite should now work in more environments.

**Comment by rich0** [comment]
@a-detiste @nabijaczleweli 
> The test suite should now work in more environments.

I should have commented earlier.  Thanks - I noticed the split, and I've enabled the nounshare tests on Gentoo (they pass).  v2.1.3 was deployed to the Gentoo repo for testing yesterday.
