### ISSUE TITLE
systemd-crontab-generator slows down systemd's boot

### ISSUE THREAD

**Issue by mikken** [systemd-cron/systemd-cron#43]
Here in Arch it takes a lot of time (approximately 1 minute) to boot until I remove the file:
/usr/lib/systemd/system-generators/systemd-crontab-generator
With the file removed it takes a few seconds.
I browsed the journal with "debug" argument passed to kernel but I don't see any errors, just the delay during boot...
Uninstalled the software for now, but I'll debug further if you tell me how.

**Comment by kstep** [comment]
There's nothing to debug. Have you read this? https://github.com/systemd-cron/systemd-cron-next/blob/master/README.md. I'll let me cite myself here:

> Still I beared in mind the image of the project's future: rewrite it in systems language. Python, being VM-based scripting language is not the best choice for system service: it's slow (**the slowest systemd generator ever, actually**), have problems with multithreading, requires a lot of hacks like setgid/setuid C helper to implement crontab, etc.

That's it: crontab generator is written in python, while all other generators are in C. It was started as a prototype for personal use, and eventually grew up and was adopted by systemd-cron project.

**Comment by kstep** [comment]
You may want to try systemd-cron-next. I started it as a better rewriting of systemd-crontab-generator, when in systems language (Mozilla's Rust). It's not finished yet, and I don't have enough free time to finish it unfortunately due to my day job, but the main functionality works for me, and only build system and package builds for different OSes are left on to-do list. It's still alpha, so all bets off, but it works on my home server for at least half a year now, so it may work for you.

**Comment by a-detiste** [comment]
Hi,

If you still are interrested in debugging you can run `/usr/lib/systemd/system-generators/systemd-crontab-generator /tmp` . (but then at this point all FS are mounted, so the bug is maybe not reproducible)

My own fix for the python-related problems would have been to rewrite it in C or C++;
but I don't feel like spending hours on this to win 1 second per day.
I wasn't even interrested in crontabs back then, mostly in learning Python & Debian packaging.

**Comment by kstep** [comment]
FYI, I published [systemd-cron-next](https://aur.archlinux.org/packages/systemd-cron-next/) package to AUR. It's now running on my server and work laptop. Feel free to try it out and check if it works for you. It should be much much more faster than python version.

**Comment by kstep** [comment]
Just a thing to check. Maybe your issue is not due to systemd-crontab-generator itself, but because of some unit it generates. Check your crontabs, including installed with third-party packages ones.

E.g. I've met an issue with [pcp](https://aur.archlinux.org/packages/pcp/) package, which installed several crontabs into `/etc/cron.d`, and they run really slow commands, which affected my startup time when systemd-crontab-generator built units on them, making them run on boot. This way if you remove/disable crontab generator, these commands wouldn't run, so it may seem crontab generator is the reason of slowdown, while it's just allows other slow things to run.

**Comment by mikken** [comment]
I remember the generator was slow even with no cron jobs installed at all.
I switched to systemd-cron-next now, it runs smoothly.

**Comment by kstep** [comment]
Glad to hear it! Please feel free to [post an issue](https://github.com/systemd-cron/systemd-cron-next/issues) to @systemd-cron-next if you find any problems!
