### ISSUE TITLE
non-ending cron job are not started

### ISSUE THREAD

**Issue by muwlgr** [systemd-cron/systemd-cron#66]
I have a non-ending script in a user's home directory : 

~$ cat tunnel.sh
while :
do ssh -o BatchMode=yes -R10022:localhost:22  user1@somehost.home.ua
done

which I start in detached screen session as @reboot cron job : 

~$ crontab -l
@reboot screen -d -m sh tunnel.sh

that's to provide reverse ssh tunnel to access a system placed behind NAT

My system in Ubuntu 18.04 LTS with all updates, cron is 3.0pl1-128.1ubuntu1 and systemd-cron is 1.5.13-1
And I am unable to migrate this cron setup to systemd-cron. No screen process is spawned on system boot. Can you please find out why ? To me, the setup looks very simple. The only specific is that this crontab line spawns non-ending screen process which becomes a daemon. Can there be any problems with cgroups ? Now I can fix that only by moving from systemd-cron back to original cron.

**Comment by trentbuck** [comment]
I'm a nosy bystander.
I'm not sure what the actual fault is there.
Using screen in this way used to be very common, but I never dug into exactly what its environment/pty requirements are for the `SCREEN` process.  Looking at a unit generate by systemd-cron, nothing obvious jumps out at me (e.g. no SystemCallFilter=).

If you want to bypass the problem instead of fixing it, you can write a systemd unit in ~/.local/, or use autossh:
https://wiki.archlinux.org/title/OpenSSH#Automatically_restart_SSH_tunnels_with_systemd

You might also find tmux (instead of screen) has better errors and support community.

If port forwarding (DNAT) is an option, consider wireguard or mosh.
https://en.wikipedia.org/wiki/WireGuard
https://en.wikipedia.org/wiki/Mosh_(software)

**Comment by a-detiste** [comment]
`systemd-cron` is not meant to launch daemon processes
