### ISSUE TITLE
cron-hourly.timer:10: Unknown key name 'ConditionPathExists' in section 'Timer', ignoring.

### ISSUE THREAD

**Issue by gyakovlev** [systemd-cron/systemd-cron#71]
systemd 246

printing this warning with v1.5.15 / https://github.com/systemd-cron/systemd-cron/commit/b59afa494a610cc20c2419af703765f1674ad05f

probably `ConditionPathExists=/run/systemd/use_run_parts` was supposed to go into `cron-schedule.service.in`  and not timer unit?

**Comment by a-detiste** [comment]
It should got in the "[Unit]" block instead.

some example:

root@brix:/home/tchet# cat /lib/systemd/system/fstrim.timer
[Unit]
Description=Discard unused blocks once a week
Documentation=man:fstrim
ConditionPathExists=/etc/fstab
ConditionVirtualization=!container

[Timer]
OnCalendar=weekly
AccuracySec=1h
Persistent=true
RandomizedDelaySec=6000

[Install]
WantedBy=timers.target

Le jeu. 5 nov. 2020 à 06:25, Georgy Yakovlev <notifications@github.com> a
écrit :

**Comment by perkelix** [comment]
Actually, a bunch of units need updating since systemd 247:

[   43.789346] systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!
[   43.824795] systemd[1]: /lib/systemd/system/cron-monthly.timer:10: Unknown key name 'ConditionPathExists' in section 'Timer', ignoring.
[   43.842885] systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!
[   43.855693] systemd[1]: /lib/systemd/system/cron-weekly.timer:10: Unknown key name 'ConditionPathExists' in section 'Timer', ignoring.
[   43.873034] systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!
[   43.889299] systemd[1]: /lib/systemd/system/cron-daily.timer:10: Unknown key name 'ConditionPathExists' in section 'Timer', ignoring.
[   43.906479] systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!
[   43.919358] systemd[1]: /lib/systemd/system/cron-hourly.timer:9: Unknown key name 'ConditionPathExists' in section 'Timer', ignoring.
[   43.936967] systemd[1]: /lib/systemd/system/cron-failure@.service:11: Special user nobody configured, this is not safe!

**Comment by gyakovlev** [comment]
^ nobody warning been there on 246 as well, here's debian bug for that
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969329

**Comment by a-detiste** [comment]
For 'Special user nobody configured, this is not safe!' I have no idea... running as root disable this warning, but well...

**Comment by trentbuck** [comment]
FTR, https://github.com/systemd-cron/systemd-cron/commit/be4aea647bce9a0f26c9b8126f7883dd5c0b60a2 fixes the internal use of User=nobody.

The "don't use User=nobody" warning will still fire when a crontab asks for nobody explicitly, e.g.

    * *  * * *  nobody  echo hello world

I don't think anything can be done about that.

**Comment by a-detiste** [comment]
Problem does not exists in current version
